---
title: "Aula 4 - GGPlot e Facet_Wrap/grid"
output: html_notebook
---

GGPLOT
ggplot(data = <DADOS>)+ geom_FUNÇÃO(mapping = aes(x =<eixo x>, y = <eixo y>, outros mapeamentos))

size: tamanho
shape: forma

```{r}
library(tidyverse)

?mpg #o ? antes do comando apresenta informações sobre ele
mpg # base de dados padrão do R




```
```{r}
ggplot(data = mpg)+geom_point(mapping = aes(x= displ, y= hwy))
ggplot(data = mpg)+geom_point(mapping = aes(x= displ, y= hwy, color = trans))
ggplot(data = mpg)+geom_point(mapping = aes(x= displ, y= hwy, color = class))
```
```{r}
ggplot(data = mpg)+geom_point(mapping = aes(x= displ, y= hwy, size = class))
```
```{r}
ggplot(data = mpg)+geom_point(mapping = aes(x= displ, y= hwy, shape = class))
```

```{r}
ggplot(data = mpg)+geom_point(mapping = aes(x= displ, y= hwy, shape = class), color = "blue")

```

Facet_wrap & Facet_Grid

```{r}

ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y= hwy, color = trans)) + 
  facet_wrap(~class, nrow=2)
```
```{r}
ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y= hwy, color = class)) + 
  facet_grid(~drv ~cyl )


ggplot(data = mpg) +
  geom_point(mapping = aes(x= displ, y= hwy, color = trans)) + 
  facet_grid(~drv ~cyl )
```
```{r}
diamonds #base de dados do R

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x=cut, fill = cut)) 



ggplot(data = diamonds) +
  geom_bar(mapping = aes(x=cut, fill = clarity), position = "fill") 

#Atribuindo Cores
cor = c("red","yellow","black","blue","green")

ggplot(data = diamonds) +
  geom_bar(mapping = aes(x=cut, fill = cut), fill = cor)




```
```{r}

```

