---
title: "R Aula 5"
output: html_notebook
---
CORREÇÃO DA ATIVIDADE 

```{r}
library(tidyverse)
diamonds

ggplot(data = diamonds) + geom_point(mapping = aes(x=carat, y=price, color = cut))

ggplot(data = diamonds) + geom_point(mapping = aes(x=carat, y=price, color = clarity))

ggplot(data = diamonds) + geom_bar(mapping = aes(x=color, fill=clarity))+ facet_wrap(~cut)
```
```{r}
#pipe

x = c(1:10)

x

mean(x)

x %>% mean()
```

Acessando dados do Banco Central
```{r}
install.packages("rbcb")
library(rbcb)

ipca = rbcb::get_series(c(IPCA = 4503), last = 100, as = "ts")
ipca
```
Manilulação de Dados
Dplyr
  Select, filter, mutate, group_by

```{r}
install.packages("dplyr")
library(dplyr)

ds = read.csv('http://codeasmanuscript.org/states_data.csv')
ds
```
Seleção de Colusas
```{r}
ds2 = ds
ds2 %>% select(Population,Income,Area)
```

```{r}

ds2 %>% select(StateName,contains('tude'), starts_with('HSG'))

ds2 %>% select(matches('Pop|Sta|HSG'))
```

Renomear Colunas
```{r}

ds2 %>% rename(Pop = Population)



```
Filtragem de Linhas
```{r}
ds2 %>% select(StateName, Population, Illiteracy, Income, Area, Region) %>% filter(Illiteracy < 2, Population> 10000)

ds2 %>% select(StateName, Population, Illiteracy, Income, Area, Region) %>% filter(between(Income, 1000,4000))
```
Criar Novas Colunas (MUTATE)
```{r}
ds2 %>% mutate(Teste = "yes", Rico = ifelse(Income > 5000, "Sim","Não")) %>% select(StateName,Population,Income,Rico)

```
Modificar Campos de colunas

```{r}
ds2 %>% select(Region) %>% mutate(
  Region = gsub(pattern = '^S', replacement = 'L&P', Region),
  Region = gsub(pattern = 't$', replacement = '__' , Region)
)
 
```
Remover Colunas

```{r}

ds2 %>% select(-Region, -matches('itude'), -Division, -Frost, -Murder)

```
Gather e Spread: Transformam colunas em linhas

```{r}
library(tidyr)

dados_juntos = ds2 %>% 
  select(StateName, Population, Income, Murder) %>% 
  gather(Medida, Valor, -StateName) 

dados_juntos %>% 
  spread(Medida, Valor)

```
Group_by
```{r}
ds2 %>% select(-Division, -Region, -StateName, -matches('itude')) %>% gather(Medida, Valor) %>%
  group_by(Medida) %>%
  summarise(Media = mean(Valor),
            DesvioPadrão = sd(Valor),
            Mediana = median(Valor),
            observacoes = n())
```

Junção de Tabelas

```{r}
df_1 = ds2 %>% select(StateName, Population)
df_2 = ds2 %>% select(StateName, Area, Income)

left_join(df_1, df_2, by = 'StateName')

```

```{r}

df_3 = ds2 %>% select(StateName, Murder) %>%
  filter(Murder < 3)
df_3

df_4 = ds2 %>% select(StateName, Income, Area)

right_join(df_3, df_4)


```

```{r}

left_join(df_3, df_4)

```

Unite e Separate

```{r}

df_4
df_junto = df_4 %>% unite("Renda e Area", sep = "|", Income, Area)
df_junto

df_junto %>%
  separate("Renda e Area", c("Renda", "Area"), sep = "|")
```

